version: "3"
services:
    ui:
        build: .
        container_name: ui
        ports:
            - "3000:80" # map 80 in container => 3000 in local
        environment:
            VIRTUAL_HOST: docker.amireux.asia
        stdin_open: true
        tty: true
        # volumes:
        #     - ./:/app
        #     - /app/node_modules
networks:
    default:
        external:
            name: nginx-proxy